### ISSUE TITLE
compatibility / requirements

### ISSUE THREAD

**Issue by joshp23** [SonOfSkywalker/lights_sync_home_assistant#2]
This requires `mss v10.0.0`, `numpy v1.26.4`, and `pillow 11.0.0` which all require at least python 3.9. The README currently calls for python 3.x and should be updated to reflect this.  

Additionally, the requirements contains `json`  is not found in pip. Is it a core element of python?

**Comment by SonOfSkywalker** [comment]
Thank you for your issue, I fixed it
